### ISSUE TITLE
Httpclient has circular dependency with OidcAuth

### ISSUE THREAD

**Issue by leandrorosa** [Apicurio/apicurio-common-rest-client#94]
There is a circular dependency between `JdkHttpClient` and `OidcAuth`. This is causing confusion while using the client. 
Please provide some examples in the docs or create dedicated clients to Auth and Registry. 

In the end I was able to make it work: https://gist.github.com/leandrorosa/b8af58cc9134f8c75b30b32e601d1056

Docs: https://www.apicur.io/registry/docs/apicurio-registry/2.2.x/getting-started/assembly-using-the-registry-client.html

**Comment by EricWittmann** [comment]
Ping @carlesarnal

**Comment by carlesarnal** [comment]
Hi @leandrorosa. I'm sorry, but I do not see the circular dependency. The HTTP client itself (either jdk or vert.x) depends on a common module, that contains the auth related classes (among other things). That other module cannot be used on its own. We have plenty of [examples](https://github.com/Apicurio/apicurio-registry-examples) of how to use our tooling, and more specifically on how to use the Apicurio Registry client (that relies on this library). 

I'm closing this one now, if you do not agree, please, re-open.
